### ISSUE TITLE
Github Enterprise (GHE) App deployed successfully, but no status checks shown on PR

### ISSUE THREAD

**Issue by ivandov** [zeke/semantic-pull-requests#157]
I've deployed this on a local server in our enterprise intranet. I configured the application on the Github side, and I'm seeing the server receive webhook events for various activities.

However, I am not seeing it register the webhook for a PR being created. And, in the PR for the repo, it's not showing the new status check being performed by the deployed app/bot.

I tried to grant privileges matching the public app on github.com, but maybe I'm missing some of the proper permissions or events to watch for?

Is there more specific documentation around what permissions the created app must be granted to be functional? Any way to test this more directly?

**Comment by cyberhck** [comment]
first thing to do would be to check your logs, on your account when you tried setting this up, go to the application's settings page, there you'll find bunch of events that were triggered (or not).

If the events were triggered but non 200 status code was returned, then the issue is on your deployment side, I'll need more info on what was returned to help you with that.

If the events weren't even triggered then there's something wrong with your installation OR no one is using your app yet.

Please note: there must be a semantic.yml file in order for this to report checks if I understand correctly.

**Comment by cyberhck** [comment]
it should look something like this: 
![image](https://user-images.githubusercontent.com/3640284/134449564-1e8b6160-6c6c-4568-b1d0-206a0a30ea92.png)

**Comment by ivandov** [comment]
I was able to see the events in the installed Apps view on Github with successful deliveries, response code `200`. 

The server side logs were also showing the requests coming in and the `200` response codes. 

I'll attempt to grab logs for this tomorrow. 

However, your comment below goes against what is documented in the `README`
> Please note: there must be a semantic.yml file in order for this to report checks if I understand correctly.

In the `README`:
> By default, no configuration is necessary.
> 
> If you wish to override some behaviors, you can add a semantic.yml file to your .github directory with the following optional settings:

**Comment by cyberhck** [comment]
ahh, maybe I'm wrong about that file then, grab the logs and let's see what's what :)

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
