### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by tysonkamp** [zeke/semantic-pull-requests#173]
Can the [node engine version](https://github.com/zeke/semantic-pull-requests/blob/021ebc531acdbd9fa882acb9371ecf480a65d17b/package.json#L43) be bumped to something more recent than "8"?  Perhaps 12, 14, 17...

**Comment by zeke** [comment]
Yeah that's a good idea. Are you able to open a pull request for this?

**Comment by tysonkamp** [comment]
I am not.  I tried the update locally and ran the tests which passed but pushing the branch to origin failed.  Are the privileges that need to be granted to my account for this repo to push a branch?

**Comment by zeke** [comment]
@tysonkamp you'll need to fork this repo to your own account, make the changes on your fork, then open a pull request from your fork.

Here are some docs on how to do that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by tysonkamp** [comment]
@zeke I don't have access/ability to see where the failure is happening when bumping the node engine version.  Is it time efficient to bump the version to something like 12, then 15, etc, and see when it fails and then I could see if I can determine from the node release notes what the issue might be?

**Comment by zeke** [comment]
Reading the Node.js release notes is not likely to be helpful. Too much going on.

I suspect the issue here is that we're running an older version of the `probot` or `probot-config` npm packages which may not be compatible with newer versions of Node.js. It could also be one of the other dependencies being incompatible.

I don't have the time to debug this right now, but you can give this a try yourself by cloning the repo, running it locally, and trying it out by running different versions of Node.js on your system, using a tool like `nvm` or `nave`. Here are some docs about how to run and use Probot apps: https://probot.github.io/docs/development/

To emulate the production setup, you'll need to:

1. deploy this app using Heroku or Vercel or similar
2. Create a new GitHub app
3. point that GitHub App at your service
4. install your GitHub app on your repo

**Comment by tysonkamp** [comment]
Hi @zeke, my fork works running locally with node v 16.14.0.  Does this information help?

tysonkamp@Tysons-MacBook-Pro-2 semantic-pull-requests % node --version
v16.14.0
tysonkamp@Tysons-MacBook-Pro-2 semantic-pull-requests % cat package.json| grep node
    "node": "16"
tysonkamp@Tysons-MacBook-Pro-2 semantic-pull-requests % npm ls  
semantic-pull-requests@0.0.0-development /Users/tysonkamp/github/tysonkamp/semantic-pull-requests
├── @octokit/rest@15.9.4
├── conventional-commit-types@3.0.0
├── jest@23.4.0
├── nock@9.4.2
├── parse-commit-message@4.0.0-canary.20
├── probot-config@1.0.0
├── probot@7.5.3
├── semantic-release@12.4.1
├── smee-client@1.2.2
└── standard@12.0.1

**Comment by zeke** [comment]
Glad to hear it's working locally. Were you able to set up a GitHub App for it and actually install it on a test repo?

**Comment by tysonkamp** [comment]
ping @zeke, do you think this is worth trying again since I couldn't reproduce the issue you saw when merging my change the last time?  If not, do you propose any next steps?

**Comment by tysonkamp** [comment]
Closing. No resolution.
