### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by zeke** [zeke/semantic-pull-requests#21]
What iconography could be used to represent "semantic pull requests"? 🤔 

Here's what the current icon looks like:

![icon](https://user-images.githubusercontent.com/2289/43289244-3cd5e152-90df-11e8-9e94-9e3e29c38fee.png)

**Comment by C0ZEN** [comment]
![icons8-pull-request-64](https://user-images.githubusercontent.com/10194542/82933814-d2410080-9f8a-11ea-8e5c-a208a21abc76.png)

**Comment by C0ZEN** [comment]
PNG:

![icons8-pull-request-50](https://user-images.githubusercontent.com/10194542/82934227-73c85200-9f8b-11ea-9e1e-5d476f6529a9.png)

SVG:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50pt" height="50pt" viewBox="0 0 50 50" version="1.1">
<g id="surface4190910">
<rect x="0" y="0" width="50" height="50" style="fill:rgb(94.509804%,76.862745%,5.882353%);fill-opacity:1;stroke:none;"/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 15 8 C 15 10.40625 13.273438 12.4375 11 12.90625 L 11 37.09375 C 13.273438 37.5625 15 39.59375 15 42 C 15 44.75 12.75 47 10 47 C 7.25 47 5 44.75 5 42 C 5 39.59375 6.726562 37.5625 9 37.09375 L 9 12.90625 C 6.726562 12.4375 5 10.40625 5 8 C 5 5.25 7.25 3 10 3 C 12.75 3 15 5.25 15 8 Z M 25 3 L 25 7 L 32 7 C 34.972656 7 37.621094 8.457031 39.257812 10.691406 L 38.640625 11.308594 L 37.835938 12.121094 C 36.585938 10.238281 34.441406 9 32 9 L 25 9 L 25 13 L 23.375 13 L 23.09375 12.78125 L 18.09375 8.78125 L 17.125 8 L 18.09375 7.21875 L 23.09375 3.21875 L 23.375 3 Z M 41 37.09375 C 43.273438 37.5625 45 39.59375 45 42 C 45 44.75 42.75 47 40 47 C 37.25 47 35 44.75 35 42 C 35 39.59375 36.726562 37.5625 39 37.09375 L 39 28.171875 L 41 26.1875 Z M 7 8 C 7 9.667969 8.332031 11 10 11 C 11.667969 11 13 9.667969 13 8 C 13 6.332031 11.667969 5 10 5 C 8.332031 5 7 6.332031 7 8 Z M 20.3125 8 L 23 10.15625 L 23 5.84375 Z M 7 42 C 7 43.667969 8.332031 45 10 45 C 11.667969 45 13 43.667969 13 42 C 13 40.332031 11.667969 39 10 39 C 8.332031 39 7 40.332031 7 42 Z M 37 42 C 37 43.667969 38.332031 45 40 45 C 41.667969 45 43 43.667969 43 42 C 43 40.332031 41.667969 39 40 39 C 38.332031 39 37 40.332031 37 42 Z M 37 42 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 45.027344 9.421875 C 44.027344 9.421875 43.128906 9.820312 42.328125 10.519531 L 42.128906 10.621094 L 42.027344 10.71875 L 41.027344 11.71875 L 40.828125 11.921875 L 29.128906 23.71875 C 29.027344 23.820312 28.929688 24.019531 28.828125 24.121094 L 27.128906 30.121094 C 26.929688 30.621094 27.226562 31.21875 27.828125 31.320312 C 28.027344 31.421875 28.226562 31.421875 28.328125 31.320312 L 34.328125 29.71875 C 34.527344 29.71875 34.628906 29.621094 34.828125 29.421875 L 47.628906 16.621094 L 47.929688 16.421875 C 49.527344 14.820312 49.527344 12.21875 47.929688 10.621094 C 47.128906 9.71875 46.027344 9.421875 45.027344 9.421875 Z M 45.027344 11.421875 C 45.527344 11.421875 46.128906 11.621094 46.527344 12.019531 C 47.328125 12.820312 47.328125 14.019531 46.628906 14.820312 L 43.726562 11.921875 C 44.128906 11.621094 44.527344 11.421875 45.027344 11.421875 Z M 42.226562 13.320312 L 45.226562 16.320312 L 34.328125 27.21875 L 31.328125 24.320312 Z M 30.328125 26.21875 L 32.429688 28.320312 L 29.527344 29.121094 Z M 30.328125 26.21875 "/>
</g>
</svg>
```

**Comment by zeke** [comment]
Hey @C0ZEN thanks for the mockups!

I like the second one. I wonder though what they'll look like in the context of a pull request page, where they'll be much smaller and perhaps harder to recognize. Can you try mocking them up in that context?

**Comment by C0ZEN** [comment]
**Some thoughts:**

- Color contrast is very good but the yellow a bit flashy for me 🟡
- Using a circle is problematic with GitHub allowing .png with transparent background but force to use a white background anyway `style="background-color: #ffffff"` (as seen as an action there is a white background and I do not like it very much due to the grey background surrounding the logo - check image below)
- The second logo is indeed not perfect for the GitHub action (the pen is not visible enough I think) - check image below

**Current logo used for the GitHub action:**
https://avatars1.githubusercontent.com/in/9517?s=40&v=4

**Current logo display from the GitHub action:**
![chrome_mPcEq4dbXk](https://user-images.githubusercontent.com/10194542/82984832-37304100-9ff3-11ea-947b-d913b7d3672f.png)

**Second logo display from the GitHub action:**
![chrome_RDAjnTtxYV](https://user-images.githubusercontent.com/10194542/82985774-eb7e9700-9ff4-11ea-9d58-dcba59b39afe.png)

@zeke multiple questions here:

- [ ] Do you wish to keep the same colors?
- [ ] Do you wish to keep the logo as a circle?

**Thoughts:**
I like the "PR schema" in the logo I provided but adding to it the notion of "this project check the semantic" is very hard due to not having enough space 😭 
This idea could be provided with a color change (classical red/green to show that it "validates") but honestly I am not seeing this with a sexy eye.
I will provide another shot at this later but any advice is welcome 🙄 

I just crossed this issue and provided a quick logo but please do not feel the need to change the logo if you are not confident enough about these propositions. You have all the time to find the perfect one 😄

**Comment by C0ZEN** [comment]
![icons8-pull-request-48](https://user-images.githubusercontent.com/10194542/82990335-554e6f00-9ffc-11ea-9a5b-d893bf257e71.png)
![icons8-pull-request-48-v2](https://user-images.githubusercontent.com/10194542/82990340-567f9c00-9ffc-11ea-92b1-30de913a0425.png)

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
