### ISSUE TITLE
Validate the optional ! before : for breaking change. 

### ISSUE THREAD

**Issue by kanitw** [zeke/semantic-pull-requests#51]
According to https://www.conventionalcommits.org/en/v1.0.0-beta.4/, commits can have "optional !" in the subject "to draw attention to breaking change".

However, currently the bot doesn't validate when we include !.

**Comment by zeke** [comment]
Ahh, right! I'm excited about this new development in the Conventional Commits spec.

I'd be happy to help support for this in semantic-pull-requests, but I think the change will probably need to be implemented in https://github.com/tunnckoCoreLabs/parse-commit-message -- I would suggest opening an issue or pull request there.

cc @tunnckoCore

**Comment by tunnckoCore** [comment]
Ahh, right, thanks for pinging me. 

If I'm honest I definitely don't like this spec addition. When it was merged? Where it was discussed? Can you give me some links, I clearly missed that ;/

Yes, it will be a small change. [It's here.](https://github.com/tunnckoCoreLabs/parse-commit-message/blob/master/src/header.js#L40)

**Comment by zeke** [comment]
> When it was merged? Where it was discussed? Can you give me some links

- https://github.com/conventional-commits/conventionalcommits.org/pull/134
- https://github.com/conventional-commits/conventionalcommits.org/pull/152
- https://www.conventionalcommits.org/en/v1.0.0-beta.4/#commit-message-with-optional-to-draw-attention-to-breaking-change

The reason I like this change is that it paves the way to a future where people don't have to write BREAKING CHANGE in the commit body to signal a breaking change. This will make it easier for newcomers to start adhering to the spec, as most people always write single-line commit messages, and hardly anyone uses the "body" when committing.

**Comment by tunnckoCore** [comment]
I totally disagree with that. Specs are not to be easy for newcomers, they are up there for combining and standardizing the things among the biggest part of a community - in this case, us the developers which have experience and we are not newcomers. Also, currently it's pretty clear and easy enough - type, scope, subject, body.

And yes, I agree and understand that most of us don't use the body when committing, even more we don't put scope most of the time. But breaking change is something that should be carefully done and hard to do, that's one point why it's uppercased.

If we are going to do it simple why just don't remove everything and just make the spec to handle only the header part.

> paves the way to a future where people don't have to write BREAKING CHANGE in the commit body to signal a breaking change

If that gets agreed I'll stop updating the parser to adhere to the spec. I can update it now just because both `!` and `BREAKING CHANGE` are required now (from what I'm understanding from the spec)

I'll look at the discussions.

**Comment by bcoe** [comment]
so, for the record, I think that the spec should be updated such that if `!` is present, there's not need for `BREAKING CHANGE`; this is how I've found myself using the new functionality in the tooling I'm writing.

I've actually updated the next version of the spec to reflect this, we just haven't promoted it to the main page yet:

https://github.com/conventional-commits/conventionalcommits.org/commit/df6de8261b3c1da7b3fa1dd209c3018bfc5b0e8b

**Comment by tunnckoCore** [comment]
I'm heading to the parser in coming days too.

**Comment by tunnckoCore** [comment]
Erm... @zeke, hi, do you remember where we were using and commenting the very latest updates? The `4.0.0-canary.20` is the last version in the canary branch. Sadly enough, I can't remember/find from where I published it. There's only a "dist" copy in npm and unpkg :D

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
